### ISSUE TITLE
Thanks for providing this! Any chance you can update it to reflect the new updates?

### ISSUE THREAD

**Issue by bimdas** [emrahtoy/StyleTTS-WebUI.pinokio#1]
Looking forward to the "Split and combine paragraphs to generate audio for text of any arbitrary length" feature that was recently added.

**Comment by emrahtoy** [comment]
Thank you for informing @bimdas .
I have just updated the repository and the Pinokio scripts.
You can either update your existing Pinokio script or delete and install it from the start.
